export const MESSAGE_UPDATE = "MESSAGE_UPDATE";
export const USER_INFO = "USER_INFO";
export const SET_COMPONENT_COM = "SET_COMPONENT_COM";
export const RESET_COMPONENT_COM = "RESET_COMPONENT_COM";

export const CMPT_SEARCH_VAL = "CMPT_SEARCH_VAL";
export const CMPT_SEARCH_LENGTH = "CMPT_SEARCH_LENGTH";
export const CMPT_SEARCH_PAGE_ADD = "CMPT_SEARCH_PAGE_ADD";
export const CMPT_SEARCH_PAGE_BELOW = "CMPT_SEARCH_PAGE_BELOW";
export const CMPT_SEARCH_SET_OBJECT = "CMPT_SEARCH_SET_OBJECT";

export const PROCESS_INIT = "PROCESS_INIT";
export const PROCESS_SERIAL_INFO = "PROCESS_SERIAL_INFO";
export const PROCESS_INFO = "PROCESS_INFO";
export const PROCESS_STATUS_UPDATE = "PROCESS_STATUS_UPDATE";
export const PROCESS_ITEMS_SET = "PROCESS_ITEMS_SET";

export const WORKS_INIT_DAY_PROCESS = "WORKS_INIT_DAY_PROCESS";
export const WORKS_EDIT_WORK_DAY = "WORKS_EDIT_WORK_DAY";

export const WORK_ABOUT_SET = "WORK_ABOUT_SET";

export const SET_MODEL_COM = "SET_MODEL_COM";

export const PDCT_ABOUT_SET = "PDCT_ABOUT_SET";
